set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'

# Set vi-mode
set-window-option -g mode-keys vi

# Windows starting from 1
set -g base-index 1
set -g pane-base-index 1

# Vi-mode Keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

set  -g default-terminal "tmux-256color"
set -ag terminal-overrides ",alacritty:RGB,xterm-256color:RGB,gnome*:RGB"

# Let applications inside tmux send OSC sequences (incl. OSC 52 clipboard) to the terminal
set -g allow-passthrough on

# Enable tmux clipboard integration (OSC 52)
set -g set-clipboard on

# Prefix
set -g prefix C-Space
set -g mouse on

# Reload config
unbind r
bind r source-file ~/.config/tmux/tmux.conf

run '~/.tmux/plugins/tpm/tpm'

# UI
set -g @background "#010409"
set -g @foreground "#f0f6fc"
set -g @dimmed "#8b949e"
set -g @accent_bright "#2f81f7"
set -g @green "#238636"
set -g @green_bright "#3fb950"
set -g @black "#0d1117"
set -g @border "#30363d"

# Status bar
set -g status-style "bg=#{@background},fg=#{@foreground}"

set -g status-position top
set -g status-justify left

set -g window-status-style "bg=#{@background},fg=#{@dimmed}"
set -g window-status-current-style "fg=#{@foreground},bold"
set -g window-status-separator " "

set -g window-status-format " #I: #W "
set -g window-status-current-format " #I: #W "

# Panes
set -g pane-border-style "fg=#{@border}"
set -g pane-active-border-style "fg=#{@foreground}"

# Messages
set -g message-style "bg=#{@black},fg=#{@foreground}"

# Copy mode
set -g copy-mode-match-style "bg=#{@green},fg=#{@foreground}"
set -g copy-mode-current-match-style "bg=#{@green_bright},fg=#{@black}"

# Status left
set -g status-left "#{?client_prefix,#[bg=#{@accent_bright}],}#[fg=#{@foreground},bold] #S "

# Status right
set -g status-right "#[bg=#{@background},fg=#{@foreground}] %H:%M #[fg=#{@dimmed},bold] %Y-%m-%d "
